name: Pull requests
# Controls when the workflow will run
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t darthvictor/udemy-docker1 -f Dockerfile.dev .
      - run: docker run -e CI=true darthvictor/udemy-docker1 npm test
